---
- hosts: webservers 
  become: true
  vars:
    apache_package: apache2
    document_root: /var/www/html

  tasks:
    - name: Install Apache2
      apt:
        name: "{{ apache_package }}"
        state: present

    - name: Deploy Static Website
      copy:
        src: index.html
        dest: "{{ document_root }}"

